name: telemetri
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  go_router: ^14.0.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.18.1
  fl_chart: ^0.70.2
  table_calendar: ^3.0.9
  mobile_scanner: ^6.0.7
  file_picker: ^10.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    # - assets/icons/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
